version: "3.8"

services:
  mongo-waitlist:
    image: mongo
    container_name: mongo-waitlist
    command: mongod --replSet rs0
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - ./db-mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./db-mongo/mongo-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password

networks:
  mongo-cluster:
